allow-external-apps = true

# Shortcut Session
shortcut.create-session = ctrl + t
shortcut.next-session = ctrl + 5
shortcut.previous-session = ctrl + 4

# Extra Keys dengan format yang lebih "clean"
extra-keys = [ \
  ['ESC', \
   {key: '/', popup: '\\'}, \
   {key: '-', popup: '|'}, \
   'CTRL', 'UP', 'ALT', \
   {key: 'PGUP', popup: '$'}, \
   {key: 'KEYBOARD', popup: {macro: "CTRL d", display: "EXIT"}} \
  ], \
  ['HOME', 'END', 'TAB', 'LEFT', 'DOWN', 'RIGHT', 'PGDN', 'BKSP'] \
]
